### ISSUE TITLE
_groupDefs is gone?

### ISSUE THREAD

**Issue by y-nk** [uNmAnNeR/imaskjs#107]
Hi !

I've been using a lot your project since 2~3 months, but, for a reason unknown, i don't have access to `input.maskRef.masked._groupDefs` anymore... Did you change something on that matter ? The components i worked on are now all broken as well, for different reasons... Are there some breaking changes since v4 ?

**Comment by uNmAnNeR** [comment]
Hi! Thanks for using `imask`!
In v4 i did many improvements mostly on pattern mask. So groups is gone in v4 and also other breaking stuff is described here: https://github.com/uNmAnNeR/imaskjs/releases/tag/v4.0.0
I did not descibe private properties, but probably you can use `_maskedBlocks` instead `_groupDefs`. But they are not the same. Items in `_maskedBlocks` are complete instances of `Masked`. There is no more `PatternGroup`.

**Comment by y-nk** [comment]
oh nooo... I was using the pattern groups to navigate through groups with keyboard (because of the selection/offset/length) properties... is there a way to find back the data related to the groups?

**Comment by uNmAnNeR** [comment]
It is not a good idea to use private methods, because they might be changed accidentially.
But if you still want to, then `MaskedPattern` has `_blockStartPos(blockIndex)` method to get block offset and `_mapPosToBlock(pos)` to get block for position. Length probably is just `block.mask.length`.
What else?
