### ISSUE TITLE
Decimal number when submitted is with comma not dot

### ISSUE THREAD

**Issue by awgul** [uNmAnNeR/imaskjs#109]
Hey,
I use `Number` mask and when I submit a field I get comma instead of dot.
How to change it?

So the question would be how to submit unmasked value?

**Comment by uNmAnNeR** [comment]
Hi, please provide more details.

**Comment by awgul** [comment]
When I have a form like

`<form><input type='text' name='money' id='money'><button>submit</button></form>`
And
` new IMask(document.getElementById('#money'), {
      mask: Number,
      thousandsSeparator: ' '
    });
`
And when I submit the form the POST `money` field has value for example `10,20` instead of `10.20`.
Displayed is of course comma but should be saved dot.

**Comment by uNmAnNeR** [comment]
@awgul Browser and me does not think so :) You send what you see, this is obvious behavior. Mask does not relate to forms or submitting, just input, other stuff is on application side. Btw if you want to send other values then subscribe on `submit` event and do your custom stuff manually.

**Comment by awgul** [comment]
Yes, but on the demo page there is the view of `unmasked` value. So I thought that unmasked value should be sent.
Because we have the `Number` format and there are different formats for US or Germany.
In US we use `comma` and i Germany `dot` as separator. But when storing data there is used `dot`.

**Comment by uNmAnNeR** [comment]
@awgul oh, got. But no :) I still think it is application side to decide what to send, not library. In plugins we've done such behavior to decide which value to store in model. But in core there is no way to control parent form, it is hard to do and very buggy at least. Input should be controlled by form, but not vice versa. So mask is managing just local store. And if you want to submit unmasked values then prevent default `submit` event and submit unmasked values manually. And please if you will do, share with community - I might add this case as example in a guide.

**Comment by ArtemProkopenko** [comment]
Hi @uNmAnNeR,

There is a question related to this topic. The documentation describes the method: mask.destroy() - **Clean** and destroy. It sounds as if applying this method should cancel the mask applied. 
This could be an alternative solution for current thread. 

Is this a bug or expected behavior? https://codepen.io/bushart/pen/PooOrNy

**Comment by uNmAnNeR** [comment]
@ArtemProkopenko hi

i thought about this. May be it should leave unmasked value in field after destroying, like some other masking libs do. But i decided to keep it as is, first because of nobody likes breaking changes and second thing is that `imask` use case is different than popular `jquery` based (or similar) solutions. The scope of `imask` is SPA primarly, and i've never tackled with such issues before. Can you please describe you case exactly? May be i missed something, please explain widely why this is important to have. It's not a big deal to implement it.

**Comment by ArtemProkopenko** [comment]
I need to use these masks on many classic forms in a classic application (it isn't SPA). Therefore, interaction with the model is unnecessary trouble in my case.
The way in which I would simply reset all the masks before sending the data looks easier than replacing the data in the request before sending it (But, apparently, I will have to figure out how to automate this process globally.)
Thanks anyway, your library is amazing (just a paradise after competitors).

**Comment by uNmAnNeR** [comment]
you are welcome :)

But! if you have number, you still will not get it, because input values are just strings. How do you solve it?
Also you are lucky if there is no need to recreate it after destroing again :)

**Comment by ArtemProkopenko** [comment]
If you are interested in this case:
My the client-side part depends on the user's locale and can format numbers for different locales (Or even add a mask of different currencies).
For example en_Us: 1,000.00 
For example de_DE: 1.000,00 
For example de_CH: 1'000.00
For example de_CH with currency: CHF 1'000.00

While the server-side expects strictly en_Us locale for operating with this data without regard to the locale.

So, I can't use the input as a raw string.
