### ISSUE TITLE
[iOS] [React] incorrect cursor position on focus

### ISSUE THREAD

**Issue by ivanov-v** [uNmAnNeR/imaskjs#123]
https://monosnap.com/file/OsPumxqjKHIZmKnTyESHbGY1PVJ9ng

**Comment by uNmAnNeR** [comment]
@ivanov-v I don't think I can fix it. On focus it sets cursor in first position and mask aligns it to first editable char. It works correct. Other scenarious is hard to implement even to detect properly.
If you'd like you can investigate it more and add more details, but for it's just "as is"

**Comment by ivanov-v** [comment]
@uNmAnNeR on the desktop browser, cursor placed at the end of the line with focus. https://monosnap.com/file/UvyWEWbNucoABcfRkfJJaDhae82zla

**Comment by uNmAnNeR** [comment]
@ivanov-v what `imask` does on focus is simply alignes cursor to nearest editable char. Somehow on IOS cursor on focus is at start position of the input, not at the end as on desktop. So it gets aligned to the nearest char at begining.
I don't want to:
1) detect IOS (probably with browser)
2) on focus force cursor at the end, because it will broke desktop users

Any ideas?

**Comment by howlettt** [comment]
This may be the related to an issue I'm seeing in Microsoft Edge:
- Navigate to the demo page (https://unmanner.github.io/imaskjs/)
- Enter a phone number into the second field (pattern)
- Focus another field
- Attempt to click in the middle of the entered phone number
- Edge moves the cursor to the start of the field, Chrome & Firefox place the cursor where you clicked
