### ISSUE TITLE
0 doesn't update nativeElement

### ISSUE THREAD

**Issue by szegedia** [uNmAnNeR/imaskjs#134]
First of all thank you for this cool plugin.
I've found an issue in angular-imask directive. It doesn't update the nativeElement if the unmask property is `typed` and the model is 0.

sample [here](https://stackblitz.com/edit/angular-wcl8uc?file=app%2Fapp.component.ts)

I think the problem is that the number mask initialize it's own value to 0 (`Number('')`) so if the model is 0 it doesn't detect the change.

**Comment by uNmAnNeR** [comment]
thanks for reporting!

Plugin checks if value was changed and then updates dom value. Yes, you are right, the problem is that `Number('') === 0`. Currently I don't know how to fix it and keep update check working.
I can cast empty string to NaN, but probably it will add more problems then solve. Let me think.
