### ISSUE TITLE
How to configure IMask for an optional value with mix and max

### ISSUE THREAD

**Issue by Mrks83** [uNmAnNeR/imaskjs#149]
Hi

Given that you have Number mask with min=0.5 and max=10.5, at the moment you can't leave the input empty (or clear the input) even its optional (not required). It will default to 0.5 and enter that value. 
How shall I configure IMask for an optional input to get empty results? Any ideas?

Thanks

**Comment by Mrks83** [comment]
A setting I'm looking for is something a "allowEmpty = true" or "optional = true", having a behavior as follows:

If value is provided and larger than max => correct to max value
else if value is provided and larger than min => value entered
else if value is provided and lower than min  => correct to min value
else => empty value (show mask).

At the moment the else (no value provided) branch leads to a min, but if and only if min is greater than 0.

**Comment by uNmAnNeR** [comment]
@Mrks83 ok. Currently you can use `Dynamic` mask when first mask matches empty and second mask is your number mask. But you pushed me to think one more time on this behaviour and now it seems for me a little bit odd. I tend to allow empty values for all numbers, but not sure. Still what if i want specific range but getting zero just because `Number('')=0`. For such cases may be `NaN` or `null` is applicable, but it seems too radical. Hm...
