### ISSUE TITLE
Warning to refresh

### ISSUE THREAD

**Issue by infantito** [uNmAnNeR/imaskjs#15]
When I do `imask.destroy()` , clear the input value, do `focus()` and then I do another `new IMask` and right away I write, It throws this warning...

![image](https://user-images.githubusercontent.com/9045302/33507561-635e2e5a-d6c3-11e7-8cee-3a187f2f2e10.png)

**Comment by uNmAnNeR** [comment]
@infantito it should be fixed now.
But probably you want to use
`imask.updateOptions({mask: <your new mask>});`
instead of recreating it.

**Comment by adriana45silva** [comment]
First let me thank you for the amazing mask \o/

And sorry to comment on a closed issue, but since my question is related... how to properly clear the input fields without breaking imask/getting the warn?
I'm configuring `imask.updateOptions({mask: <your new mask>});` with the exact configurations as the instance, removing the instance with `destroy()` and manually cleaning the input value. Am I missing something?

I've already tried `reset()` method instead of the  `destroy()`, but it cleanses only the model, not the UI (and when I clean the UI manually I get the warning)

` applyMask(applyMask){

    let input = document.querySelector('.skills-input');
 
    let myInput = new IMask(
        input,
        {
          mask: Number,
          min: 0,
          max: 10,
        });

        myInput.updateOptions({
          mask: Number,
          min: 0,
          max: 10
        });

      if (!applyMask){
        myInput.destroy()
        myInput.value = ''
      }
  }`

**Comment by uNmAnNeR** [comment]
thanks!

Mask is created and destroyed once, but could be updated many times.
Consider to use different handlers for creating, updating and destroying.
Currently major frameworks go this way (React, Angular, Vue) providing lifecicle hooks. This is prefered.
Usually when mask is once applied it is stored somewhere, and then it could be updated.
In your example mask is just local variable and there is no way to determine has mask already applied or not.
But rewriting your example:
```
function applyMask (isInitialized, applyMask) {
  if (!isInitialized) // init...
  else if (!applyMask) // destroy...
  // update
}
```
Also note that updating only makes sense if options change.

There are also examples with different handlers in plugins folder.
