### ISSUE TITLE
react-imask does not preserve symbol after the mask

### ISSUE THREAD

**Issue by volodymyrhudyma** [uNmAnNeR/imaskjs#174]
Hi!

I have the following mask:
 
```
mask={[
 {
    mask: 'num EUR',
    blocks: {
         num: {
             mask: Number,
             max: 99999,
             thousandsSeparator: ' ',
         },
      },
   },
]}
```

It seems to be working fine except that the currency symbol is shown only after pressing any not numeric key. I have seen an issue here that describes the same problem and you suggested using` lazy: false` here, so I tried and had no success.

Could you help with this issue?

P.S.

If I change `mask: 'EUR num',`, it seems to be working as expected.

**Comment by uNmAnNeR** [comment]
Hi!
make sure `lazy: false` is in right place, check this one: https://codepen.io/anon/pen/pmoYjy
if this is working but react plugin is not, then let me know and i'll check plugin.

**Comment by uNmAnNeR** [comment]
Also i'am not sure about wrapping mask in `[...]` in your example.

**Comment by volodymyrhudyma** [comment]
Thanks for such a quick response :)

Unfortunately, when I remove `[...]` - the mask is not applied at all. Adding lazy doesn't help as well. 

I see your example works prefectly fine, so maybe a small bug in react plugin.

**Comment by uNmAnNeR** [comment]
ok, i will check

**Comment by uNmAnNeR** [comment]
@volodymyrhudyma It seems i've found why it does not work in your case. Because in react-imask `mask` property is just mask (string), not mask options (object), other properties are placed alongside, e.g.:

```jsx
mask={'num EUR'}
lazy={false}
blocks={{
  num: {
    mask: Number,
    max: 99999,
    thousandsSeparator: ' ',
  },
}},
```

just like in example here: https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask

**Comment by volodymyrhudyma** [comment]
Thanks, that seems to help!

**Comment by mauriciogirardi** [comment]
Hello, I’m trying a placeholder and with the symbol at the end, but when I type the value the symbol does not appear, so that I can use the placeholder the lazy is true,  when false works more the placeholder does not appear,

Can you tell if I’m doing something wrong or is it some problem with lib?
