### ISSUE TITLE
Date mask can reach state from which no valid date can be entered

### ISSUE THREAD

**Issue by tbroadley** [uNmAnNeR/imaskjs#18]
(Please feel free to close this issue if you don't think it's a bug!)

To reproduce:

- Visit https://unmanner.github.io/imaskjs/
- Type "311220" into the date input

Expected behaviour: In this state, I wouldn't expect to be able to enter 2. After entering 2, any possible way of filling out the final digit of the year would result in a date after 31-12-2020.

Actual behaviour: I am able to enter 2. After entering 2, I can't enter a final digit.

**Comment by uNmAnNeR** [comment]
Yes, it seems like a bug, but
Date mask is designed to be very flexible and extendable, e.g. pattern option could be:
`pattern: 'Y/m/d'` or `m/d/Y` or any other
And the most generic way to check date bounds is to construct date from complete input and to compare dates.
It might be possible partially compare once day, then month, then year, etc. But probably we just get overcomplicated code, bugs, increased library size and still can not determine when it is possible to do.
For these reasons i did not do it in core. I think Date mask should be treated as a last wall and commonly user does not reach it. Because convinient hints and common sense are also usually used together with a mask.
Finally, it is possible to provide custom `validate` function where more strict custom conditions like in this case could be checked.
This is not the first question on that topic.
Hope my answer helps.

**Comment by tbroadley** [comment]
I think you're right that trying to fix this sort of edge case would make the date mask more complicated for little benefit. Thanks for the explanation!
