### ISSUE TITLE
ctrl+v decimal value with integer options

### ISSUE THREAD

**Issue by FallenMireq** [uNmAnNeR/imaskjs#186]
Hello.

I have "imasked input" with option `scale: 0`.

But when I'm trying paste **decimal** value (e.g. `123.321`), imask will ignore radix and result will be `123321`. As for me expected value should be `123`.

[Live example on stackblitz](https://stackblitz.com/edit/typescript-yh9tnu)

Also correct rounding is welcome :)
(I mean: for value `123.987` expected result should be `124`).

**Comment by uNmAnNeR** [comment]
input is just text for imask. What it is trying to do is to insert all available numbers. I don't think it's a good idea to analize input in some way, because this just very specific case. Let imaging if user has value with thousand separators `123 321` or separator is comma `123,321`, and there are many other cases, so let's keep it simple. You can always do custom processing in `prepare` option.
