### ISSUE TITLE
Vue stateless example doesn't work as expected

### ISSUE THREAD

**Issue by Solant** [uNmAnNeR/imaskjs#189]
Example from https://github.com/uNmAnNeR/imaskjs/tree/master/packages/vue-imask#mask-stateless-example allows entering any characters to masked input

Example: https://codesandbox.io/embed/vue-template-79t3v

![Screenshot_20190531_131008](https://user-images.githubusercontent.com/5971578/58699123-6e9aec00-83a5-11e9-8a73-160ccf53514b.png)

**Comment by uNmAnNeR** [comment]
Hi! Yes PRs are always welcome!
As for me i don't use this approach, because it picks only masking stuff leaving implementing input interaction on developer. I prever using vue components.
The problem here is that `phone` is not updated after input is complete, therefore view is not updated and masked getter is not called. Here is an issue in Vue about it: https://github.com/vuejs/vue/issues/214

The workaround could be to add some intermediate change: https://codesandbox.io/s/imask-vue-stateless-example-39g8l
But still there are issues with cursor positioning while input in the middle.
So just use it on your own risk, this example just goes 'as is' and more about starting point to extend `imask`  rather than complete working solution.

**Comment by Solant** [comment]
Thank you for the response
Looks like there is also an issue with `v-model` being `:value` `@input` under the hood.
Probably it can be fixed with several events on input like `keydown`, `paste` and so on, but it is basically the same as reimplementing the whole `vue-imask`

I was trying to use it on the already existing Input component, so I can keep all existing stuff there, without proxying all user input through a directive

As this example works not quite as expected, can I create PR to remove it, or just add a warning there?

**Comment by uNmAnNeR** [comment]
already removed. thanks!
