### ISSUE TITLE
Number mask strange behaviour with zero

### ISSUE THREAD

**Issue by shrpne** [uNmAnNeR/imaskjs#205]
Some examples of strange behaviour with imask Number type, they can be reproduced in the imask website demo https://unmanner.github.io/imaskjs/guide.html#number
I have tried different options and looks like they don't affect this behaviour. So it is reproduced with any combination of options.
imask version: 5.1.6

Type in the empty input: "01"
Actual result: "0"
Expected result: "1" or "01"

Type in the empty input: ".1"
Actual result: ".1"
Expected result: "0.1"

**Comment by uNmAnNeR** [comment]
hi!
1) mask is about restricting input, not about fixing it. So i just don't want to guess what user wants while input "01". May be this is typo, may be he forgot comma, but i think number can not start with 0 in common sense.

2) It allowed to input ".1" because deletion operation should be able to do it: `0.1 -> (remove 0) -> .1`. Imask works with input snapshots, not operations like insert or delete, which makes it very powerfull, but also admits such cases. Anyway zero is added on blur and i think it's good enough.

btw i am sure there are a lot more checks which could be added in case of any mask and imask provides abilities to extend any mask: `validate` and `prepare` callbacks. So it's possible to achieve what you describe, but probably not in core. I'd like to keep it simple.

**Comment by shrpne** [comment]
Thank you for explanation
