### ISSUE TITLE
Replace please phone example with correct solution

### ISSUE THREAD

**Issue by a-x-** [uNmAnNeR/imaskjs#214]
Internet is full of ugly bad phone number formatters/validators. It's much better to create inputs w/o a bad formatters.

imask's example shows bad practice that people copies w/o a minimal thinking.

I found and tested good library specifically for a phone numbers: [react-phone-number-input](https://github.com/catamphetamine/react-phone-number-input).
it's works good with many cases, at least:
- pasting either from clipboard or autocompleter
- international and local numbers
- any phone number formats
- _for more strict validation maintainer recommends a libphonenumber-js lib additionally_

Add a strict recommendation to use it instead of imask for phone numbers solution, please.

Some formats are hard and should not be covered with universal tool

And thank you for a awesome library! We use it for many simple and medium formatters.

**Comment by a-x-** [comment]
https://unmanner.github.io/imaskjs/guide.html#pattern
<img width="1062" alt="Screenshot 2019-07-06 at 19 44 07" src="https://user-images.githubusercontent.com/6201068/60758976-6da14e00-a026-11e9-82a2-235475f2514c.png">

**Comment by a-x-** [comment]
Meanwhile, we created own wrapper over imask and other libraries for formatting and validation fields in react.

**Comment by a-x-** [comment]
**Note**. the react-phone-number-input should be used with `showCountrySelect={false}`.

It's makes it looks more like a usual imask-react inputs

**Comment by uNmAnNeR** [comment]
Hi! Not sure i get you right, but what do you mean saying 'imask's example shows bad practice'?
Phone number example is about using mask pattern mostly, not about masking phones. I don't provide here solution for masking phones, espesially for people that 'copies w/o a minimal thinking'. I chosen phone number for example because it of the most frequently used one. And i know at least several people for whom it is good enough just it as is in example. For others imask provides so many ways to extend out of the box.
So imask is about masking in general and phone number is just example. What is bad here?

**Comment by a-x-** [comment]
Add please a caution to phone mask example, that it's not production ready and for good phone masking special libraries should be prefered

**Comment by a-x-** [comment]
I described a problems and some libraries to prefer for phone number case
