### ISSUE TITLE
IMask doesn't prevent incorrect key input in Firefox

### ISSUE THREAD

**Issue by solidevolution** [uNmAnNeR/imaskjs#221]
We use your vue directive to imask a phone number with this options:

```
{ mask: '{+00} 000 0000000000000' }
```

Works great in chrome and safari but in firefox, also non numeric keys exists in masked field.
[see video](https://www.marcelmueller.de/firefox_imask.mp4)

Are there known problems with imask and firefox?

**Comment by uNmAnNeR** [comment]
I have not heard about any issues in firefox until now. Firefox is quite stable :) Mask works only with `text` type. Make sure it is `text`.
Also I was not able to reproduce it in firefox (https://unmanner.github.io/imaskjs/guide.html#pattern -> demo). Please create some fiddle to run online if you need more help, because this issue may be related to vue only.

**Comment by uNmAnNeR** [comment]
feel free to reopen if you will need more help!

**Comment by vmrfriz** [comment]
@uNmAnNeR, is there a solution for type="number"? I have not found another way to open numeric keypad on a mobile phone
