### ISSUE TITLE
Caret bug in dynamic masks

### ISSUE THREAD

**Issue by MaximStone** [uNmAnNeR/imaskjs#231]
Here I have an example https://jsfiddle.net/3s8ejnar/5/ 

If you using 5.2.0 version and trying to input phone number 8 800 111 11 11, input caret just changed it position to 0 when dynamic mask switched to another.

When you using 5.1.5 (did not check with other versions) - it works fine.

**Comment by uNmAnNeR** [comment]
On input in `dispatch` callback unmasked value is not updated yet.
So in your example cursor is aligned incorrectly, because on `input` event there is old `unmaskedValue`, but `appended` is not empty. And after input was changed it computes cursor position there is new `unmaskedValue` but empty `appended`.
So you have to choose mask considering `appended`, thats why it goes first argument:

https://jsfiddle.net/uNmAjs/jnhatcug/

**Comment by MaximStone** [comment]
My mistake, I've lost that argument and missed your guide.

Thanks a lot! 

This version works well for me https://jsfiddle.net/me40gsnc/

**Comment by MaximStone** [comment]
I have another bug you can reproduce here https://jsfiddle.net/unp6ztmg/

Can you help to find out the problem?

In my example above you see only one dynamic mask, but there are many others in my project. I just skipped them, because bug stable reproduced without them.

Thanks!

**Comment by MaximStone** [comment]
@uNmAnNeR Need you help)

**Comment by uNmAnNeR** [comment]
@MaximStone sorry for long delay, needed to relax a little bit. So don't modify `masked` in callback, just select. It should be free of side effects. It calls several times during updating value. So if i just removed
```
    if (!val) {
      dynamicMasked.reset();
      return;
    }
```
it works. Try to find different solution without side effects.

**Comment by MaximStone** [comment]
Thank you!
