### ISSUE TITLE
Copy paste issue + Cursor issue in case of Decimal values 

### ISSUE THREAD

**Issue by efatima** [uNmAnNeR/imaskjs#241]
1. Copy/Cut paste the following value in the input field:  `$43555` (or any value with $ sign).
 If i remove the digits one by one, $ sign **should get** automatically removed. (same as when i type the value instead of copy pasting it and remove digits one by one) [JSFiddle Link](https://jsfiddle.net/s8w5rpm3/1/).
Is there any way to achieve this?
**Note: It works when i don't copy the $ sign.**

2. I have a currency input field with some minimum and maximum value. [JSFiddle Link 2](https://jsfiddle.net/gnr0785t/)
  Try entering `333`, now press another digit, the cursor moves to the beginning and now 
   we have to manually move the cursor to input decimal values. How can i avoid that?
**Note: This cursor does not move to beginning when i have an input field that does not have decimal values.**

**Comment by uNmAnNeR** [comment]
1. Inside imask tracks what chars were input by user. In first case $ is user input in first case that's why imask does not removes it automatically. This feature is used a lot in complex dynamic masks, but in this case seems to be unnessessary. Need to investigate how to fix it carefully.

2. bug!

thanks a lot for reporting
