### ISSUE TITLE
Pattern Masks: Delete a letter, deletes all following letters/numbers

### ISSUE THREAD

**Issue by TimGr** [uNmAnNeR/imaskjs#276]
Hi @uNmAnNeR, thank you for this great plugin  :)
I'm not quit sure, but I think I found a little bug using pattern masks. Please have a look at this demo:
https://codesandbox.io/s/vanilla-jtryb

**Steps to reproduce:**
1. Focus input and delete any number = works like expected.
2. Focus input and delete one of the letters = every following number/letter appearing after the position of the deleted letter gets deleted. 

Would be great to have your feedback on this :) Thank you.

**Comment by uNmAnNeR** [comment]
Hi! you are welcome!

Actually this is expected behavior. By default pattern mask enables `lazy` mode in which mask does not keep chars positions. There are 2 ways to make it work:
1) use `lazy: false` (but get placeholder)
2) use backquote to prevent char shifting back

Example here: https://codesandbox.io/s/vanilla-2kmn9

**Comment by TimGr** [comment]
Hi, thank you for your fast answer. 
Now it works like expected. Thank you :)
