### ISSUE TITLE
(Bug|Fixing) Safary Iphone 5; undefined is not an object (evaluating 'this.globalThis = this')

### ISSUE THREAD

**Issue by cvaize** [uNmAnNeR/imaskjs#300]
TypeError: undefined is not an object (evaluating 'this.globalThis = this')
![image](https://user-images.githubusercontent.com/26907947/74416334-d5463400-4e66-11ea-8d26-ab6d17e063ed.png)
![image](https://user-images.githubusercontent.com/26907947/74416394-e5f6aa00-4e66-11ea-9088-edd3301c11ef.png)
![image](https://user-images.githubusercontent.com/26907947/74416441-f73fb680-4e66-11ea-9700-bc05f21e04b7.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/74416574-29e9af00-4e67-11ea-9e74-5d365e9f76ad.png)
Highlighted an error, it's in the library

**Comment by cvaize** [comment]
FIX!!!!! ADDED `import 'core-js/features/global-this';`
![image](https://user-images.githubusercontent.com/26907947/74421040-38879480-4e6e-11ea-8783-4775dce8f004.png)

**Comment by uNmAnNeR** [comment]
Hi. here is the same thing https://github.com/uNmAnNeR/imaskjs/issues/296 check it.
I am closing this also because that there are no additional information on issue.
I just repeat it again:
Ok, the problem exists and you guys probably want me to fix it. But i don't. Because i use `globalThis` lib just as described in a guide, and built code is exactly the same as in library. So why the problem is in IMask?
And also even i'd like to support good old iphone 5 and miriads of other devices, i don't have so much time to go deep into this. I don't have mac and iphone 5 also. Don't you think i should buy it to debug this open source which is completly free for everyone and brings no benefit to me at all?
So you have a problem, figure it out and do a PR. Otherwise just believe me, it will never be fixed.

**Comment by uNmAnNeR** [comment]
`import 'core-js/features/global-this';` does pretty the same, it's better to figure out why current solution does not work

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/74421293-9ae09500-4e6e-11ea-9d24-2f820d9b155d.png)

**Comment by cvaize** [comment]
Please accept the pull request, and rebuild

**Comment by uNmAnNeR** [comment]
@cvaize have you read the article https://mathiasbynens.be/notes/globalthis ?
This solution seems much better then core-js does. So i am not sure it's a good idea to use core-js.
But ok, if we go on with `core-js`. I checked your PR. It's nice, but it should also care about removing old approach. I don't think we should have both side by side.

**Comment by cvaize** [comment]
@uNmAnNeR I think you're right

**Comment by cvaize** [comment]
@uNmAnNeR I found an interesting dependency 
![image](https://user-images.githubusercontent.com/26907947/74425858-31648480-4e76-11ea-9af6-cd44fe7bb30f.png)
![image](https://user-images.githubusercontent.com/26907947/74425946-51944380-4e76-11ea-8d46-af369af0e18d.png)
![image](https://user-images.githubusercontent.com/26907947/74425988-5f49c900-4e76-11ea-90fc-b6cf8340b412.png)

**Comment by cvaize** [comment]
@uNmAnNeR Please accept the pull request and rebuild dist for npm

**Comment by jgelo** [comment]
Looks like this update causes an issue with MS Edge -

`'globalThis' is not defined`

Reverting back to 6.0.1 for now.
