### ISSUE TITLE
ReferenceError: globalThis is not defined in old browsers

### ISSUE THREAD

**Issue by OliverWall** [uNmAnNeR/imaskjs#313]
Hi.
Big thanks for you libriary. It very comfortable and functionallity libriary.

Problem:
I developed react component using react-imask ^6.0.0, but i found a bug in production of several users who use old browser.

**Example** 

Workspace:
[mozilla 58.0](https://ftp.mozilla.org/pub/firefox/releases/58.0/) or other old browser
[test application for you](https://github.com/OliverWall/test)

Run app in firefox.

ErrorMessage: _ReferenceError: globalThis is not defined_

What can i do? I have several users in production and they get this error, because of this I can't use your library =(

Will Its possible fix in next release?

**Comment by stijnbollen** [comment]
I recently updated my imask library from 6.0.1 to 6.0.3 and ran into the same problem.
Clients using old browsers and IE will get the same reference error.

**Comment by OliverWall** [comment]
Do I understand correctly that globalThis will be removed in the next release 6.0.4?

**Comment by uNmAnNeR** [comment]
Hello guys! Thanks for using imask and helping to improve it.

Since 6.0.0 only `umd` build contains polyfills. If you are using bundlers then probably you are using `es` build. So you have to include polyfills manually according to environment you want to support.
List of all polyfills to support down to ie 11 is here: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/polyfills.js
As you can see, there are some more options except `globalThis`.

Here is interersting discussion about polyfilling: https://github.com/w3ctag/polyfills/issues/6#issuecomment-272647475

@OliverWall no, `globalThis` will be here
@stijnbollen #296 is little bit different but directed me to exclude `globalThis` along side with other polyfills.

Please don't close this issue until it will be in a guide. I can't get why this still is not described. Really sorry about that.

**Comment by OliverWall** [comment]
Thanks for answer.

I will wait for help or the guide from you. Right now i use react-imask v.6.0.3 and still get error [in this compoent](https://github.com/OliverWall/test/blob/master/src/component/PhoneInput.js). I installed package from NPM.

**Comment by uNmAnNeR** [comment]
@OliverWall 
the solution is pretty simple:
- `npm install core-js`
- copy polyfills that target platform requires from https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/polyfills.js

If you need only `globalThis` polyfill, then also this one could be used: https://github.com/ungap/global-this/

**Comment by OliverWall** [comment]
@uNmAnNeR 

Thank you very much for help and this beautiful library.

**Comment by uNmAnNeR** [comment]
fixed in #331

**Comment by Yuvarajsivam** [comment]
@OliverWall Polyfills.js is missing in the mentioned path. Could you please confirm
