### ISSUE TITLE
React Imask is not working as expected when resetting form using input type reset

### ISSUE THREAD

**Issue by devangbhuva97** [uNmAnNeR/imaskjs#394]
**Issue:** Getting this warning when trying to update value in text box after resetting the form using input type `reset` 

**Warning** `Element value was changed outside of mask. Syncronize mask using mask.updateValue() to work properly.` 

After reset if try to change the value. It appends last digit of previous(i.e. value before rest) value.

https://codesandbox.io/s/react-imask-go525

**Steps**:
1. Enter any number (e.g. 396)
2. Reset form (using input type reset)
3. Enter only single digit (e.g 4)

**Output**: 46
**Expected output**: 4

**Comment by umairhm** [comment]
Hey @devangbhuva97, I am not a pro at React, but I tried something and it seems to work fine for me. Maybe you can improve on this fork: https://codesandbox.io/s/react-imask-forked-l179j?file=/src/App.js

The actual problem is that imask maintains the input value separately, and the form reset only resets the input but the mask doesn't know about this change.

**Comment by devangbhuva97** [comment]
Thank you @umairhm for your time. Actually I was trying to implement with [react hook form](https://github.com/react-hook-form/react-hook-form) but it was not working as expected. I'll again try by taking reference from your solution.
