### ISSUE TITLE
Regex mask Vue plugin issue

### ISSUE THREAD

**Issue by ihorbond** [uNmAnNeR/imaskjs#405]
Hi! First of all thank you for all the hard work that you've put into this package, it's great! 
I have an issue with Regex in Vue plugin

```
<imask-input
          v-model="regexModel"
          :mask="/^\d+$/"
          :unmask="true" />
```
This works but if change the expression to /^\d{3}$/ it doesn't work anymore. Am I doing it wrong ?

**Comment by avrahamcool** [comment]
the problem is - that each time you put a character, the regex is evaluated - and return false.
let's say you try to input "123", the moment you type the "1" - it fails to pass the regex test - so it's discarded.
then the "2" is passed - but also fails, then the "3" and it's also discarded.

if you have a "fixed" length mask - just use the pattern mask instead of the regex mask.
`mask: "000"`

if you have to use RegEx, try to write one that evaluate to true as long as you type..
