### ISSUE TITLE
Release 6.0.6 breaks build

### ISSUE THREAD

**Issue by slubowsky** [uNmAnNeR/imaskjs#444]
Update to 6.0.6 breaks build of my app. Lots of random errors in my own components somehow but also things like:
`error TS2307: Cannot find module 'angular-imask' or its corresponding type declarations.`
and 
`Module not found: Error: Can't resolve 'angular-imask'`
Reverted back to 6.0.5 and all is well...

**Comment by slubowsky** [comment]
Wrong repo. Moving to https://github.com/uNmAnNeR/imaskjs/tree/master/packages/angular-imask

**Comment by slubowsky** [comment]
Ah, its the correct one. issues are same.

**Comment by thekip** [comment]
Looking into what installed in version 6.0.5 and 6.0.5 can say that error in happend because now sources stored in '/dist' folder and no "main" or "module" field specified in package.json

Pointing directly to the `dist` fixing the issue: 

```ts
import { IMaskModule } from 'angular-imask/dist';
```

6.0.6
![image](https://user-images.githubusercontent.com/1586852/107672481-3cbedb80-6c95-11eb-9787-c5696a47e1f4.png)

6.0.5
![image](https://user-images.githubusercontent.com/1586852/107672528-49433400-6c95-11eb-8714-f6f476020179.png)

**Comment by thekip** [comment]
Looking into commit history and don't see anything special, so may assume that package just was incorrectly published to NPM. Instead of publishing from './dist' directory, it was published from root.

**Comment by thekip** [comment]
@uNmAnNeR FYI

**Comment by uNmAnNeR** [comment]
@thekip @slubowsky thanks guys for letting me know.
pick it up `angular-imask@6.0.6-1`
