### ISSUE TITLE
Help Needed - MaskedDate different format

### ISSUE THREAD

**Issue by albert9111** [uNmAnNeR/imaskjs#454]
Hi, 

I need to mask a date and show it as `DD/MM/YYYY` but than I need to send it to the server as `YYYY-MM-DD`.
If I understood `format` and `parse` callbacks have to be `format(parse(yourDateString)) === yourDateString`.

If I set the pattern as `Y-m-d` and following [this example](https://imask.js.org/guide.html#masked-date)  it works fine but I need to change the date to show to the user using this format  `DD/MM/YYYY`

How can I do that? Thanks!

**Comment by uNmAnNeR** [comment]
hey. I think it's out of scope of the mask, since mask is about VIEW layer. so i am not going to put it in library (at least for now). you have to do it on your side.
One of solutions could be to subclass from MaskedDate and define get (or/and set) for your internal value which will transform mask value.
