### ISSUE TITLE
Vue-directive - refresh mask manually

### ISSUE THREAD

**Issue by karambafe** [uNmAnNeR/imaskjs#61]
How can I update the mask manually when using vue-directive?

My case:
```
<input
    v-imask="mask"
    :value="value"
    @accept="handleAccept"
/>

data: () => ({
    mask: {
        mask: Number,
        min: 320,
        max: 9999,
        scale: 0,
    },
}),

props: {
  value: {
      type: String,
      required: true,
    },
}

methods: {
  handleAccept(e) {
      this.$emit('onChange', e.detail.value);
    },
}
```

1. I change the value of input through the props
2. I set the cursor to the first position (this is important :))
3.  add new numbers - in console warnings 'Uncontrolled input change, refresh mask manually!'. Accept event is not always fired, return value incorrect %)

**Comment by uNmAnNeR** [comment]
@karambafe First consider using Vue-component instead of Vue-directive.
But if you still want using Vue-directive, `IMask` reference is located just inside element: `input.maskRef`.
If i understand you correctly you are changing input value directly omitting mask. After that you have to notify mask about it and do `maskRef.updateValue()` - that what means refreshing manually. Warning message does not make much sence now, I will change it.

**Comment by karambafe** [comment]
@uNmAnNeR, thanks for the answer!
After calling the method `updateValue()` the problem remained.
I found in the documentation this way: `maskRef.typedValue = newValue`. With him everything worked correctly. 
If this is the right way to solve the problem, then close issue

**Comment by uNmAnNeR** [comment]
@karambafe  yes, that is correct also

**Comment by shrpne** [comment]
Hi, @uNmAnNeR Thank you for this great plugin!
I want to discuss this issue, posting here instead of a new issue because I have the same case as @karambafe 
In my opinion, something goes wrong here. Console warning says to use `maskRef.updateValue()`, but as we can see, it is not working properly.

Steps to reproduce: 
```js
// for example I have empty input
console.log(input.value); // => ""
// changing input programmatically
input.value = "10";
// maskRef stay unchanged
console.log(input.maskRef); // { _value: "", _unmaskedValue: "", masked: { _value: "" }}
// trying to fix, as warning told
input.maskRef.updateValue();
// only masked value have changed
console.log(input.maskRef); // { _value: "", _unmaskedValue: "", masked: { _value: "10" }}
// for now, if I write something into the input by hands, console will warn me again
// and only if I use:
input.maskRef.value = "10";
// or 
input.maskRef.typedValue = "10"
// maskRef will be updated properly
console.log(input.maskRef); // { _value: "10", _unmaskedValue: "10", masked: { _value: "10" }}
```

Here I see two ways to solve this:
1. `.updateValue()` not works properly and should be fixed
2 `.updateValue()` is not intended to update maskRef after manual input change and warning message should be updated

**Comment by uNmAnNeR** [comment]
@shrpne hi, thanks :)

Actually `updateValue` works correctly. And yes, all that it does is just set masked value from input. It works well for vanilla javascript. But it does not for `Vue` or other plugins. And it should not, because in `Vue` you have model defined in your application and model is source of truth. It's strange situation when somehow input was changed, but model is not. Mask should not update application state, but should react on state changing.
So the correct behavior is to update model, and mask will update respectively.

**Comment by shrpne** [comment]
@uNmAnNeR 
Actually, I don't change input directly, I change Vue state, and Vue through `v-model` do `input.value = "vueStateValue"`.
Because with mask directive, there is no connection between Vue state and iMask state, I have to tell to the iMask that value is changed with `.updateValue()` as console warning suggests.
But the problem here, that iMask doesn't update all its state, but only masked value. 
And if now I try to write something down to the input, it will get wrong value:
instead of 
`"newVueStateValue" + "writenSymbol"`
it will be
`"oldMaskStateValue" + "writenSymbol"`

So I have Vue state updated, input's value updated, and maks's masked value updated, but it isn't enough to make iMask work properly.
And my question is: if everything works correctly, why I get buggy mask behavior? :)

**Comment by uNmAnNeR** [comment]
@shrpne if you show some working code in sandbox like jsfiddle, i will be able to give you an answer.
