### ISSUE TITLE
Bug with dinamic change 'max';

### ISSUE THREAD

**Issue by iseredov** [uNmAnNeR/imaskjs#64]
I used the component like Number mask.
If I set the "max" parameter to be less than the current value, then the last digit is cut off, instead of setting the maximum value.

**Comment by uNmAnNeR** [comment]
@iseredov  It is still input mask, which works on chars. All what it does is trying to insert new value under new conditions.
I think generally the right way to process incorrect input is not to fix it, but restrict. When user types it works ok. May be such sceme works not so good for your case, but i try to keep mask as simple as possible. I am not sure two different strategies of input processing can live together. BTW the other strategy is done by `Cleave.js`, check it out.
The second point why I dont want to fix it, because it seems that min and max options in your case relates to `model` layer, not `view`. If it is, then setting max value should also affect value in model. This is application model logic. So I suggest to detect changes on application side and update value respectively.

**Comment by uNmAnNeR** [comment]
@iseredov one more solution could be using `prepare` callback to update the value. So i close the issue.
