### ISSUE TITLE
IMaskMixin throws error when caret is not at the end

### ISSUE THREAD

**Issue by Zevgon** [uNmAnNeR/imaskjs#668]
**Describe the bug**
When using IMaskMixin, it throws an error when changing the input anywhere that's not at the end.

**To Reproduce**
1. Go to https://codesandbox.io/s/jolly-ellis-5d4r08?file=/src/App.js
2. In the first input box, input 7 numbers
3. Set the caret somewhere in the middle of the input, e.g. click between the 3rd and 4th number
4. Type one more number (or hit delete)

**Expected behavior**
The number typed in step 4 should be inserted without errors, but it throws an error:
![image](https://user-images.githubusercontent.com/18666969/167239338-727f0614-9b85-4547-a699-0d40f01c9fd3.png)

As shown with the second input, everything works just fine when using `useIMask`, which has the same mask (`'0000 0000'`)

**Environment:**
 - OS: macOS Monterey 12.2.1
 - Browser: Chrome
 - Version: 100.0.4896.127
 - IMask version: 6.4.2

**Comment by Ethorsen** [comment]
I'm having the exact same issue with a simple IMaskInput.  

Example here.   If  you position yourself anywhere in the field but the end and try to remove a char, you get an error in MaskedPattern as described above.
https://codesandbox.io/s/mystifying-wood-l7wp5t?file=/src/App.js

![image](https://user-images.githubusercontent.com/1493968/168639019-fba4f28e-59c2-4b0c-ad47-bd52329b5ca9.png)


The bug was introduced in 6.4.0. If you switch to 6.3.0 it works fine.  I will stick on that version until this is figured out.

Thx

**Comment by glow27** [comment]
I have the same error but with antd-masked-input, the PR should fix the problem

**Comment by uNmAnNeR** [comment]
fixed

**Comment by Ethorsen** [comment]
It feels like this fix deserve a release on its own. Since 6.4.2 is now in a broken/unusable state..

**Comment by uNmAnNeR** [comment]
well okay i'll try
