### ISSUE TITLE
change event in IE 11

### ISSUE THREAD

**Issue by Mobold** [uNmAnNeR/imaskjs#77]
Hi,
please have a look at this jsbin site: https://jsbin.com/bubabiyufu/1/edit?html,js,output
If you type in numbers for time in "deutsche Urhzeit: hh:mm" and hit tab then no change event is fired in Internet Explorer 11 (Windows 10). In Firefox 61 it works fine. 
Do you have an idea or is it not supported?

**Comment by uNmAnNeR** [comment]
@Mobold hi!
imask does not prevent any element events. So probably this behavior does not relates to it.

**Comment by Mobold** [comment]
I tested a bit more. Please have a look at https://jsbin.com/fefazeleku/1/edit . If you use `lazy: false` then in IE 11 no change event is fired. You can try it if you remove the comment for `lazy: false`. Do I miss something?

```javascript
var maskOptions = {
  mask: Date,
  pattern: momentFormat,
  //lazy: false,
  format: function (date) {
    return moment(date).format(momentFormat);
  },
  parse: function (str) {
    return moment(str, momentFormat);
  },
  groups: {
    HH: new IMask.MaskedPattern.Group.Range([0, 23]),
    mm: new IMask.MaskedPattern.Group.Range([0, 59])
  }
};
```

**Comment by uNmAnNeR** [comment]
@Mobold in short look what happens:
- focus field
- input something
- mask process input and **set new value**
- let blur and trigger `change` event

Good browsers trigger change event if value that was before focus and on blur was changed. But IE considers intermediate `set new value` and compares with it but not that was before focus.
So in `lazy` mode there is no intermediate value update, because values are same and mask checks it and does not do unnessessary update.
Probably I will not add any polyfills/hacks/workarounds about IE behavior, may be low level tricks exist at network.

**Comment by Mobold** [comment]
@uNmAnNeR 
Thanks for the info.
