### ISSUE TITLE
Warning when input value is changed programmaticaly

### ISSUE THREAD

**Issue by kouts** [uNmAnNeR/imaskjs#92]
First of all, thank you @uNmAnNeR for this great plugin.
I'm encountering an issue when the input is changed programmatically, I get a warning
```Uncontrolled input change, refresh mask manually!```
I'm using [Zebra_Datepicker](https://github.com/stefangabos/Zebra_Datepicker) to update the input value.

I have tried ```mask.updateValue()``` and also ```mask.typedValue = newValue``` to no avail and ```mask.masked.reset();``` doesn't help either.

I have created a fiddle here [https://jsfiddle.net/5jfghtky/8/](https://jsfiddle.net/5jfghtky/8/) if you could take a look at it, thanks.

**Comment by uNmAnNeR** [comment]
@kouts thank you :)

In your case when a date is selected from picker the event sequence is:
- change input
- focus on input
- fire `onSelect` event and we update mask value

Mask warning happens on `focus` (before `onSelect`) because mask still contains old value, but input value has already changed. So you can just ignore it. But it makes sense to update mask value before focusing input if datepicker library allows.
The correct order should be:
- change input
- update mask input
- fire `onSelect`
- focus

**Comment by kyleoliveiro** [comment]
Can we have an option to disable the warning in cases where it can be safely ignored?

**Comment by kyleoliveiro** [comment]
I'm using this plugin in a custom Vue component. I tried the vue-imask package at first using the directive, but it has issues (no two-way binding). So I'm now using vanilla imask. The updateValue function does not work, so I have to manually trigger the update but the warning still shows.

Will write up a more detailed issue report later.
